### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/ansible-role-bigiq_onboard#1]
This all looks like basic auth; if thats the case you need to enable that on the BIG-IQ before you can make these calls (dependency). 

Alternatively you could switch to auth tokens with something like below, remember that IQ auth tokens only last 5 mins or you'll need to refresh it.

- name: Get BIG-IQ Authentication Token from {{bigIqCM}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{bigIqCMAdmin}}","password":"{{bigIqCMPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{ bigIqCM_mgmt_pip }}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigIqCM_auth_response

- name: Assign Auth Token to Variable
  set_fact:
    bigIqCM_auth_token: "{{ bigIqCM_auth_response.json.token.token }}"

replace the basic in the tasks with:

    headers:
      X-F5-Auth-Token: "{{ bigIqCM_auth_token }}"

**Comment by caphrim007** [comment]
this should now be fixed
