### ISSUE TITLE
New feature request - audit log syslog servers

### ISSUE THREAD

**Issue by tizianorosato-gr** [f5devcentral/ansible-role-bigiq_onboard#11]
New feature - audit log syslog servers settings

Is it possible to add this task for BigIQ 8.x?

**Comment by rjouhann** [comment]
Hello,

You can use the [Ansible URI module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html) to set up syslog server after the onboarding is completed.


1. GET ``https://<BIG-IQ>/mgmt/cm/system/machineid-resolver?$filter=product%20eq%20%27BIG-IQ%27&state%26eq%20ACTIVE%27``

Save ``machineId``.

2. POST ``https://<BIG-IQ>/mgmt/cm/system/remote-syslog-servers``

Update ``<machineId>`` in the body.

```
{
  "port": 514,
  "state": "enabled",
  "facility": "log audit",
  "severity": "notice",
  "syslogFormat": "rfc3164",
  "transportProtocol": "tcp",
  "deviceReference": {
    "link": "https://localhost/mgmt/shared/resolver/device-groups/cm-shared-all-big-iqs/devices/<machineId>"
  },
  "properties": {
    "cm:gui:module": [
      "access",
      "adc",
      "networksecurity",
      "applicationsecurity",
      "device",
      "webclientsecurity",
      "system"
    ]
  },
  "name": "demo",
  "ipAddress": "10.1.1.5"
}
```

Thanks & Regards,
Roman

**Comment by tizianorosato-gr** [comment]
Thanks @rjouhann 
bit unrelated questions:
- where can I find the full list of BIG-IQ API ?
  published documentation is not complete apparently 
  https://clouddocs.f5.com/products/big-iq/mgmt-api/v0.0/
- can you provide examples of rest-api to configure external based authentication , such as radius,ad/ldap  ?

**Comment by rjouhann** [comment]
Hello,
This is the only place where BIG-IQ APIs are documented is the link you have above.
For undocumented APIs, I recommend to open an [SR](https://www.f5.com/company/contact/regional-offices#product-support). You could also look at the API calls made by the UI using your [browser developer tool](https://developer.chrome.com/docs/devtools/network/).
Thanks!
